# Introduction {#intro}

Welcome to the RxODE user guide; **RxODE** is an R package for solving
and simulating from ode-based models. These models are convert the
RxODE mini-language to C and create a compiled dll for fast
solving. ODE solving using RxODE has a few key parts:

 - `RxODE()` which creates the C code for fast ODE solving based on a
   simple syntax (Chapter \@ref(syntax)) related to Leibnitz notation.
 - The event data, which can be:
   - a `NONMEM` or `deSolve` compatible data frame (Chapter \@ref(events)), or
   - created with `et()` or `EventTable()` for easy simulation of events(Chapter \@ref(simulation))
   - The data frame can be augmented by adding
     time varying or adding individual covariates (`iCov=` as needed)
 - `rxSolve()` which solves the system of equations using initial
   conditions and parameters to make predictions
   - With multiple subject data, this may be
     parallelized.
   - With single subject the output data frame is adaptive
   - Covariances and other metrics of uncertanty can be used to
     simulate while solving.
	 
 
While this is the user guide, there are other places that you can visit for help:

This book was assembled on `r date()` with RxODE version 
`r packageVersion("RxODE")` automatically by github actions.
