# RxODE events {#events}

```{r child='RxODE/vignettes/events-1.Rmdh'}
```

## Bolus/Additive Doses

```{r child='RxODE/vignettes/events-bolus.Rmdh'}
```

## Infusion Doses

```{r child='RxODE/vignettes/events-infusion.Rmdh'}
```

### Constant Infusions (in terms of duration and rate)

```{r child='RxODE/vignettes/events-infusion-constant.Rmdh'}
```

### Modeled Rate and Duration of Infusion

```{r child='RxODE/vignettes/events-infusion-modeled.Rmdh'}
```

## Steady State

```{r child='RxODE/vignettes/events-steady-state.Rmdh'}
```

### Steady state for complex dosing

```{r child='RxODE/vignettes/events-steady-state-complex.Rmdh'}
```

### Steady state for constant infusion or zero order processes

```{r child='RxODE/vignettes/events-steady-state-infusion.Rmdh'}
```


## Reset Events

```{r child='RxODE/vignettes/events-reset.Rmdh'}
```

## Turning off compartments

```{r child='RxODE/vignettes/events-off.Rmdh'}
```

## Classic RxODE events

```{r child='RxODE/vignettes/events-classic.Rmdh'}
```
