# Advanced & Miscellaneous Topics

This covers advanced or miscellaneous topics in `RxODE`

## Using RxODE with a pipeline

```{r echo=FALSE, results='asis'}
cat(gsub("(^|\n) *(#+) +", "\\1##\\2 ",
         unlist(knitr::knit_child(text = readLines("RxODE/man-roxygen/rmdhunks/pipeline.Rmdh"),
                                  envir = environment(), quiet = TRUE))), sep="\n")
```

## Speeding up RxODE

```{r echo=FALSE, results='asis'}
cat(gsub("(^|\n) *(#+) +", "\\1##\\2 ",
         unlist(knitr::knit_child(text = readLines("RxODE/man-roxygen/rmdhunks/speed.Rmdh"),
                                  envir = environment(), quiet = TRUE))), sep="\n")
```

## Integrating RxODE models in your package

```{r echo=FALSE, results='asis'}
cat(gsub("(^|\n) *(#+) +", "\\1##\\2 ",
         unlist(knitr::knit_child(text = readLines("RxODE/man-roxygen/rmdhunks/packages.Rmdh"),
                                  envir = environment(), quiet = TRUE))), sep="\n")
```

## Stiff ODEs with Jacobian Specification 

```{r echo=FALSE, results='asis'}
cat(gsub("(^|\n) *(#+) +", "\\1###\\2 ",
         unlist(knitr::knit_child(text = readLines("RxODE/man-roxygen/rmdhunks/stiff.Rmdh"),
                                  envir = environment(), quiet = TRUE))), sep="\n")
```
